function LF() { echo "$1"; };
function MySQL() { mysql n2a -e "$1" | grep -v " row " | awk '{ if ($0 ~ /^: /) {print substr($0,3);} else {print $0}}'; };

LF "LISTADO DE TIPOS DE ARTICULO"; 
MySQL "select
	'' '',
	CONCAT('         TIPO:',a.ORDER_ITEM_TYPE_ID,' ',DESCRIPTION) '',
	CONCAT('BULTOS / COMBI ISOT.:',LPAD(IFNULL(b.BULKS_IN_COMBI,0),11,' ')) '',
	CONCAT('PEDIDO MINIMO:',LPAD(MIN_ORDER,18,' ')) '',
	CONCAT('CAMIONIZACION:',LPAD(IF(TRUCKING_AUTO_FLAG,'SI','NO'),18,' ')) '',
	CONCAT('TODO EL BOLETIN APROV:',LPAD(IF(FULLFILLMENT_PRINT_FLAG,'SI','NO'),10,' ')) '',
	CONCAT('TODO EL BOLETIN CAMIO:',LPAD(IF(TRUCKING_PRINT_FLAG,'SI','NO'),10,' ')) '',
	CONCAT('% LLENADO COMBI:',LPAD(FORMAT(IFNULL(COMBI_FULL_PERCENT,0),2),16,' ')) '',
	CONCAT('ACTIVACION PEDIDO AUTOM.',LPAD(IF(APT2_AUTO_FLAG,'SI','NO'),8,' ')) '',
	CONCAT('PARAMETRO H (MIN):',LPAD(GENERATE_TRANSMISION_BEFORE_MINS,14,' ')) '',
	CONCAT('PARAMETRO Y (MIN):',LPAD(TRANSMISION_BEFORE_MINS,14,' ')) ''

	FROM ORDER_ITEM_TYPE a
		LEFT JOIN ORDER_ITEM_TYPE_COMBI b ON a.ORDER_ITEM_TYPE_ID=b.ORDER_ITEM_TYPE_ID
	ORDER BY a.ORDER_ITEM_TYPE_ID\G"
