[ -z "$TIENDA" ] && source /root/functions.sh

function LF() { echo "$1"; };
function MySQL() { mysql n2a -e "$1" | grep -v " row " | awk '{ if ($0 ~ /^: /) {print substr($0,3);} else {print $0}}'; };

[ -z "$D" ] && D=0;
[ -z "$H" ] && H=999999;

LF "     LISTADO GENERAL DE ARTICULOS"; 
LF ""; 
LF "DESDE CODIGO: $D";
LF "HASTA CODIGO: $H";
LF"";
LF "---------------------------------"; 

N_ARTI=$(mysql n2a -e "select ITEM_ID from ITEM where ITEM_ID BETWEEN $D AND $H" | tail -1);
[ -z $N_ARTI ] && LF "EL RANGO DE ARTICULOS SOLICITADO NO EXISTE EN LA TPV" && exit;

if [ "${VERSION:0:2}" == "04" ] ; then
	CAPT_PESO_SUBTIPO_PESO=",CONCAT('CAPTURA PESO: ',IF(ISL.WEIGHT_SCALE_FLAG,CONCAT('SI\nSUBTIPO PESO:',IF(IST.FIXED_UNITS_FLAG=0,'PESO FIJO','PESO VARIABLE')),'NO'))";
else
	CAPT_PESO_SUBTIPO_PESO=",CONCAT('CAPTURA PESO:',IF(ISL.WEIGHT_SCALE_FLAG,'SI','NO'))";
fi;

for ARTICULO in "$N_ARTI"; do
	MySQL "SELECT
	'',
	CONCAT('<b>',RPAD(I.ITEM_ID,7,' '), I.DESCRIPTION,'</b>') ''
	,'' ''
	,CONCAT('TIPO IVA:',T.TAX_CODE,' ',RPAD(IF(IST.WEIGHT_FLAG,'KILOS','UNIDADES'),11,' '), 'VENTA:',IF(I.SALE_FLAG, 'SI','NO')) ''
	,CONCAT('TIPO:',IST.ORDER_ITEM_TYPE_ID,' ',RPAD(OIT.DESCRIPTION,11,' '), 'VEN.INTER:', IF(ISL.INTERNAL_ID_SALE_FLAG,'SI','NO')) ''
	,CONCAT('DEPARTAMENTO: ',RPAD(PD.POS_DEPARTMENT_CODE,5,' '),'SECCION: ',HIERARCHY.CODE_SECTION) ''
	,CONCAT('FAMILIA:',RPAD(HIERARCHY.CODE_FAMILY,7,' '),'SUBFAMILIA: ', HIERARCHY.CODE_SUBFAMILY) ''
	,CONCAT('MARCA:',B.BRAND_CODE,' ',B.DESCRIPTION) ''
	,CONCAT('PERTENECE AL SURTIDO: ',IF(IFNULL(AI.ITEM_ID,0) > 0, 'SI','NO')) ''
	,CONCAT('CATEGORIA: ',LPAD(C.CATEGORY_CODE,2,' '),' ',RPAD(C.DESCRIPTION,7,' '),'PEDIDO:',IF(IST.ORDERABLE_FLAG,'SI','NO')) ''
	,CONCAT('PED.MIN:',LPAD(IST.MIN_ORDER,6,' '),' PED.MAX:',LPAD(IST.MAX_ORDER,7,' ')) ''
	,CONCAT('ALM:',LPAD(W.WAREHOUSE_CODE,6,' '), '   D.T.STOCK:',LPAD(IO.STOCK_DAYS_CALC,7,' ')) ''
	,CONCAT('FECHA DST:',DATE_FORMAT(IO.STOCK_DAYS_CALC_DATE,'%d/%m/%Y')) ''
	,CONCAT('CAP.BUL:',LPAD(FORMAT(IST.BULKS_CAPACITY,2),7,' '),'  UNI/BUL:', LPAD(IF(SI.FIXED_UNITS_FLAG = 1, FUI.UNIT_BULKS_QUANTITY, IF(SI.WEIGHT_FLAG = 0, SI.BULKS_QUANTITY, 0)),5,' ')) ''
	
	,CONCAT('FOR.SERVI:',SF.SERVICE_FORMAT_CODE,' ',SF.DESCRIPTION) ''
	,CONCAT('PESO MEDIO/UNIDAD:',LPAD(FORMAT(IF(IST.FIXED_UNITS_FLAG = 1,FUI.STANDARD_WEIGHT,0),3),10,' ')) ''
	,CONCAT('TRANSFORMADO:',IF(0,'SI','NO')) ''
	,CONCAT('ES ENVASE:',IF(0,'SI','NO'),' ES ESQUELETO:',IF(0,'SI','NO')) ''
	,CONCAT('COMODATO:',IF(0,'SI','NO')) ''
	,CONCAT('ENVASE:',LPAD(0,7,' '),' ESQUELETO:',LPAD(0,7,' ')) ''
	
	,CONCAT('PVP.TARI:',LPAD(PRICE.PRICE_AMOUNT_RATE_ACTUAL,9,' '), LPAD(IF(PRICE_NEXT.PRICE_AMOUNT_RATE_NEXT IS NULL, '0.00',PRICE_NEXT.PRICE_AMOUNT_RATE_NEXT),12,' ')) ''
	,CONCAT('PVP.FIDE:',LPAD(PRICE.PRICE_AMOUNT_LOYALTY_ACTUAL,9,' '), 
		LPAD(IF(PRICE_NEXT.PRICE_AMOUNT_LOYALTY_NEXT IS NULL,'0.00',PRICE_NEXT.PRICE_AMOUNT_LOYALTY_NEXT),12,' ')) ''
	,CONCAT('PVP.NO.F:',LPAD(PRICE.PRICE_AMOUNT_NO_LOYALTY_ACTUAL,9,' '), 
		LPAD(IF(PRICE_NEXT.PRICE_AMOUNT_NO_LOYALTY_NEXT IS NULL, '0.00',PRICE_NEXT.PRICE_AMOUNT_LOYALTY_NEXT),12,' ')) ''
	,CONCAT('   P.PVP1:',IF(PRICE.PROMOTION_ACTUAL,'SI','NO'),'      P.PVP2:',IF(PRICE_NEXT.PROMOTION_NEXT, 'SI','NO')) ''
	,CONCAT('PVP.LIBRE:',IF(IP.FREE_PRICE_FLAG,'SI','NO'),'   PVP ESPEC:', IF(IP.SPECIAL_PRICE_FLAG,'SI','NO')) ''
	$CAPT_PESO_SUBTIPO_PESO ''
	,CONCAT('PESO MEDIO/BULTO:',LPAD( FORMAT(IF(IST.WEIGHT_FLAG = 1, IST.BULKS_QUANTITY, 0),3),12,' ')) ''
	,CONCAT('ETIQUETA FyV:', IF(IFL.ITEM_ID,'SI','NO')) ''
	,CONCAT('TIPO ARTICULO PEDIDO:', IO.ITEM_EXPIRATED_TYPE_ID) ''
	,CONCAT('CONTEO MAXIMO:',LPAD(FORMAT(IC.MAX_COUNT,3),9,' ')) ''

FROM
    ITEM I 
INNER JOIN
    (
        SELECT
            ISC.ITEM_ID AS ITEM_ID,
            ISC.CODE_SECTION AS CODE_SECTION,
            IFA.CODE_FAMILY AS CODE_FAMILY,
            ISB.CODE_SUBFAMILY AS CODE_SUBFAMILY 
        FROM
            ITEM_SECTION ISC 
        INNER JOIN
            ITEM_FAMILY IFA 
                ON IFA.ITEM_ID = ISC.ITEM_ID 
        INNER JOIN
            ITEM_SUBFAMILY ISB 
                ON ISB.ITEM_ID = IFA.ITEM_ID 
        WHERE
            ISC.ITEM_ID = $ARTICULO
    ) HIERARCHY 
        ON I.ITEM_ID = HIERARCHY.ITEM_ID 
INNER JOIN
    (
        SELECT
            VPRA.ITEM_ID AS ITEM_ID,
            VPRA.PRICE_AMOUNT  AS PRICE_AMOUNT_RATE_ACTUAL,
            VPRA.PROMOTION_STATUS_FLAG AS PROMOTION_ACTUAL,
            VPLCA.PRICE_AMOUNT AS PRICE_AMOUNT_LOYALTY_ACTUAL,
            VPLA.PRICE_AMOUNT  AS PRICE_AMOUNT_NO_LOYALTY_ACTUAL 
        FROM
            PRICE_RATE_ACTUAL VPRA 
        INNER JOIN
            PRICE_LOYALTY_ACTUAL VPLA 
                ON VPLA.ITEM_ID = VPRA.ITEM_ID 
        INNER JOIN
            PRICE_LOYALTY_CARD_ACTUAL VPLCA 
                ON VPLCA.ITEM_ID = VPLA.ITEM_ID 
        WHERE
            VPRA.ITEM_ID = $ARTICULO
    ) PRICE 
        ON I.ITEM_ID = PRICE.ITEM_ID 
INNER JOIN ITEM_SALE ISL ON ISL.ITEM_ID = I.ITEM_ID 
INNER JOIN ITEM_PRICE IP ON IP.ITEM_ID = I.ITEM_ID 
INNER JOIN BRAND B ON B.BRAND_ID = I.BRAND_ID 
INNER JOIN CATEGORY C ON C.CATEGORY_ID = I.CATEGORY_ID 
INNER JOIN TAXES T ON T.TAX_ID = ISL.TAX_ID 
LEFT JOIN  POS_DEPARTMENT PD ON PD.POS_DEPARTMENT_ID = I.POS_DEPARTMENT_ID 
LEFT JOIN  ITEM_COUNTS IC ON IC.ITEM_ID = I.ITEM_ID 
LEFT JOIN  ITEM_ORDER IO ON IO.ITEM_ID = I.ITEM_ID 
LEFT JOIN  ITEM_STOCK IST ON IST.ITEM_ID = I.ITEM_ID AND I.ITEM_TYPE_ID = IST.ITEM_TYPE_ID 
INNER JOIN ITEM_STOCK_BULKS_MAX_ORDER SI ON SI.ITEM_ID = I.ITEM_ID AND SI.ITEM_TYPE_ID = I.ITEM_TYPE_ID
LEFT JOIN  (SELECT DISTINCT ITEM_ID FROM ASSORTMENT_ITEMS) AI ON AI.ITEM_ID = I.ITEM_ID 
LEFT JOIN  SERVICE_FORMAT SF ON SF.SERVICE_FORMAT_ID = IST.SERVICE_FORMAT_ID 
LEFT JOIN  FIXED_UNIT_ITEM FUI ON FUI.ITEM_ID = IST.ITEM_ID AND FUI.FIXED_UNITS_FLAG = IST.FIXED_UNITS_FLAG 
LEFT JOIN (SELECT VPRN.ITEM_ID AS ITEM_ID, VPRN.PRICE_AMOUNT AS PRICE_AMOUNT_RATE_NEXT, VPRN.PROMOTION_STATUS_FLAG AS PROMOTION_NEXT, VPLCN.PRICE_AMOUNT AS PRICE_AMOUNT_LOYALTY_NEXT, VPLN.PRICE_AMOUNT AS PRICE_AMOUNT_NO_LOYALTY_NEXT  FROM PRICE_RATE_NEXT VPRN
LEFT JOIN  PRICE_LOYALTY_NEXT VPLN ON VPLN.ITEM_ID = VPRN.ITEM_ID 
LEFT JOIN  PRICE_LOYALTY_CARD_NEXT VPLCN ON VPLCN.ITEM_ID = VPLN.ITEM_ID WHERE VPRN.ITEM_ID = 68 ) PRICE_NEXT ON I.ITEM_ID = PRICE_NEXT.ITEM_ID 
LEFT JOIN  ITEM_FRESH_LABEL IFL ON I.ITEM_ID = IFL.ITEM_ID
     JOIN  WAREHOUSE W ON W.WAREHOUSE_ID = IST.WAREHOUSE_ID 
LEFT JOIN  ORDER_ITEM_TYPE OIT ON OIT.ORDER_ITEM_TYPE_ID = IST.ORDER_ITEM_TYPE_ID 

WHERE I.ITEM_ID = $ARTICULO

ORDER BY I.ITEM_ID\G";

MySQL "SELECT
	CONCAT(RPAD(SF.DESCRIPTION,10,' '),':',LPAD(FORMAT(IFNULL(IBSF.BULKS_BY_SERVICE_FORMAT,0),3),6,' ')) ''
	FROM
		ITEM I 
		INNER JOIN ITEM_BULKS_SERVICE_FORMAT IBSF ON IBSF.ITEM_ID = I.ITEM_ID AND IBSF.ITEM_TYPE_ID = I.ITEM_TYPE_ID 
		LEFT JOIN SERVICE_FORMAT SF ON SF.SERVICE_FORMAT_ID = IBSF.SERVICE_FORMAT_ID 
	WHERE
		I.ITEM_ID = $ARTICULO\G";

MySQL "SELECT
	CONCAT('COD.ARANC.:') '',
	CONCAT('GRADOS ALCOHOL:',LPAD(FORMAT(IFNULL(ILA.ALCOHOLIC_PROOF,0),2),7,' '),'   CENT:',IF(IFNULL(ILA.CENTRALIZE_STATUS_TYPE_ID,0),'SI','NO')) '',
	CONCAT('BULTO MIXTO: ',IF(I.MIX_BULK_FLAG,'SI','NO')) '',
	IF(I_S.SCALE_ITEM_TYPE_ID IS NULL,'NO BALANZA DE SECCION',CONCAT('BALANZA SECCION: ', IF(I_S.SCALE_ITEM_TYPE_ID=1,'VENTA ASISTIDA','AUTOSERVICIO'))) ''
	FROM
		ITEM I
		LEFT JOIN ITEM_LABEL_A4 ILA ON ILA.ITEM_ID=I.ITEM_ID
		LEFT JOIN ITEM_SALE I_S ON I_S.ITEM_ID=I.ITEM_ID
	WHERE
		I.ITEM_ID=$ARTICULO\G";

MySQL "SELECT CONCAT('GESTION CADUCIDAD: ', IF(EXPIRATION_MANAGEMENT_FLAG,'SI','NO')) '' FROM ITEM WHERE ITEM_ID=$ARTICULO\G";

LF "";

done
