VERS=`. /usr/bin/parse_release_info.sh  /usr/local/n2a/etc/release-info.properties`;
function LF() { echo "$1"; };
function MySQL() { mysql n2a -e "$1" | grep -v " row " | awk '{ if ($0 ~ /^: /) {print substr($0,3);} else {print $0}}'; };

[ -z "$D" ] && D=0;
[ -z "$H" ] && H=999999;

LF "    LISTADO DATOS APT2/ARTICULO";
LF;
LF "DESDE CODIGO:             $D";
LF "HASTA CODIGO:             $H";
LF;
LF " --------------------------------";
LF;

N_ARTI=$(mysql n2a -e "select ITEM_ID from ITEM where ITEM_ID BETWEEN $D AND $H" | tail -1);
[ -z $N_ARTI ] && LF "EL RANGO DE ARTICULOS SOLICITADO NO EXISTE EN LA TPV" && exit;

# if [ "${VERS:0:2}" == "04" ] ; then
	CAP_UNIDADES="CONCAT('CAP.UNIDADES:             ',LPAD(IST.UNITS_CAPACITY,6,' ')) '',";
# else
# 	CAP_UNIDADES="";
# fi;

for ARTICULO in "$N_ARTI"; do

MySQL "SELECT
	CONCAT(I.ITEM_ID,'  ', I.DESCRIPTION) as '',
	'',
	CONCAT('ALMACEN:',LPAD(W.WAREHOUSE_CODE,24,' ')) as '',
	CONCAT('ALTA PEDIDO:', LPAD(IF(IST.ORDERABLE_FLAG=0,'No','Si'),20,' ')) as '',
	CONCAT('SURTIDO:',LPAD(IF(AI.ITEM_ID <> 0,'Si','No'),24,' ')) AS ' ',
	CONCAT('LINEAL: ',LPAD(IL.SHELF,3,' '),'      ALTURA: ', LPAD(IL.HIGH,2,' ')) as '',
	CONCAT('PREVISION:',LPAD(FORMAT(IO.SALES_FORECAST,3),22,' ')) '',
	CONCAT('DST:',LPAD(FORMAT(IO.STOCK_DAYS_CALC,3),28,' ')) '',  
	CONCAT('FECHA DST:',LPAD(DATE_FORMAT(IO.STOCK_DAYS_CALC_DATE,'%d/%m/%Y'),22,' ')) '',
	CONCAT('HORA DST: ',LPAD(DATE_FORMAT(IO.STOCK_DAYS_CALC_DATE,'%H:%i'),22,' ')) '',
	CONCAT('FOR.SERVI:',LPAD(SF.SERVICE_FORMAT_CODE,22,' ')) '',
	CONCAT('CAP.BUL:  ',LPAD(FORMAT(SI.BULKS_CAPACITY,3),22,' ')) '',
	$CAP_UNIDADES
	CONCAT('U/K:      ',LPAD(IST.WEIGHT_FLAG,22,' ')) '',
	CONCAT('UNI/BUL:  ',LPAD(IF(SI.FIXED_UNITS_FLAG = 1, FUI.UNIT_BULKS_QUANTITY, IF(SI.WEIGHT_FLAG = 0, SI.BULKS_QUANTITY, 0)),22,' ')) '',
	CONCAT('BUL/FORMATO:',LPAD(FORMAT(IFNULL(SI.BULKS_BY_SERVICE_FORMAT, 0),3),20,' ')) '',  
	CONCAT('PESO M/B: ',LPAD(FORMAT(IF(SI.WEIGHT_FLAG = 1, SI.BULKS_QUANTITY, 0),3),22,' ')) '',
	CONCAT('SUBTIPO PESO:',LPAD(SI.FIXED_UNITS_FLAG, 19,' ')) '',
	CONCAT('TIPO APT2:',LPAD(SI.ORDER_ITEM_TYPE_ID, 22, ' ')) '',
	CONCAT('TIPO PEDIDO:',LPAD(IET.ITEM_EXPIRATED_TYPE_CODE,20,' ')) '',
	CONCAT('PED.MIN:',LPAD(SI.MIN_ORDER,6,' '),'   PED.MAX:', LPAD(SI.MAX_ORDER,7,' ')) '',  
	CONCAT('CONTEO MAXIMO :',LPAD(FORMAT(IC.MAX_COUNT,3),17,' ')) '',
	CONCAT('PROMOCION:',LPAD(IF(PRA.PROMOTION_STATUS_FLAG,'Si','No'),22,' ')) '',
	CONCAT('F. LIMITE DEVOLUCION: ',DATE_FORMAT(IFNULL(SI.RETURN_DATE,'0000-00-00'),'%d/%m/%Y')) '',
	'',
	CONCAT('FR:',LPAD(IF(IFNULL(FR.FR,0) > 0,'Si','No'),29,' ')) '',
	CONCAT('FC:',LPAD(IF(IFNULL(FC.FC,0) > 0,'Si','No'),29,' ')) '',
	CONCAT('FID:',LPAD(IF(IFNULL(FID.FID,0) > 0,'Si','No'),28,' ')) '',
	''

FROM ITEM I  
INNER JOIN ITEM_ORDER IO ON IO.ITEM_ID = I.ITEM_ID  
INNER JOIN ITEM_STOCK IST ON IST.ITEM_ID = I.ITEM_ID AND IST.ITEM_TYPE_ID = I.ITEM_TYPE_ID  
INNER JOIN WAREHOUSE W ON W.WAREHOUSE_ID = IST.WAREHOUSE_ID  
LEFT JOIN ITEM_LOCATIONS IL ON IL.ITEM_ID = I.ITEM_ID  
INNER JOIN ITEM_COUNTS IC ON IC.ITEM_ID = I.ITEM_ID  
INNER JOIN ITEM_EXPIRATED_TYPE IET ON IET.ITEM_EXPIRATED_TYPE_ID = IO.ITEM_EXPIRATED_TYPE_ID  
INNER JOIN ITEM_STOCK_BULKS_MAX_ORDER SI ON SI.ITEM_ID = I.ITEM_ID AND SI.ITEM_TYPE_ID = I.ITEM_TYPE_ID  
INNER JOIN SERVICE_FORMAT SF ON SI.SERVICE_FORMAT_ID = SF.SERVICE_FORMAT_ID  
LEFT JOIN FIXED_UNIT_ITEM FUI ON FUI.ITEM_ID = SI.ITEM_ID AND FUI.FIXED_UNITS_FLAG = SI.FIXED_UNITS_FLAG  
          AND FUI.ITEM_TYPE_ID = I.ITEM_TYPE_ID  
LEFT JOIN RELATED_ITEMS RI ON RI.ITEM_ID_FROM = I.ITEM_ID AND RI.RELATIONSHIP_TYPE_ID = 2 AND RI.DELETE_FLAG = 0  
LEFT JOIN RELATED_ITEMS RI2 ON RI2.ITEM_ID_TO = I.ITEM_ID AND RI2.RELATIONSHIP_TYPE_ID = 2 AND RI2.DELETE_FLAG = 0  
LEFT JOIN (SELECT ITEM_ID, COUNT(*) FR FROM ITEM_CORRECTION_FACTOR ICF WHERE ICF.FACTOR_TYPE_ID = 5 GROUP BY ITEM_ID) FR ON FR.ITEM_ID = I.ITEM_ID  
LEFT JOIN (SELECT ITEM_ID, COUNT(*) FID FROM ITEM_CORRECTION_FACTOR ICF WHERE ICF.FACTOR_TYPE_ID = 6 GROUP BY ITEM_ID) FID ON FID.ITEM_ID = I.ITEM_ID  
LEFT JOIN (SELECT ITEM_ID, COUNT(*) FC FROM ITEM_CORRECTION_FACTOR ICF WHERE ICF.FACTOR_TYPE_ID <> 5 AND ICF.FACTOR_TYPE_ID <> 6 GROUP BY ITEM_ID) FC ON FC.ITEM_ID = I.ITEM_ID  
LEFT JOIN (SELECT DISTINCT ITEM_ID FROM ASSORTMENT_ITEMS) AI ON AI.ITEM_ID = I.ITEM_ID  
INNER JOIN PRICE_RATE_ACTUAL PRA ON PRA.ITEM_ID = I.ITEM_ID  
WHERE I.ITEM_ID = $ARTICULO AND I.ITEM_ID NOT IN (SELECT ITEM_ID FROM DISPLAY_UNIT_ITEM) AND I.ITEM_ID NOT IN (SELECT ITEM_ID FROM PARTY_ITEM)
ORDER BY I.ITEM_ID\G";
done;
